---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/5/23 14:27
---

function test()
    print("test")
end

local a = 5
local b =7
local c = a+b
print(c)
test()